project_name: event-reporter
dist: dist

release:
  github:
    owner: TheCacophonyProject
    name: event-reporter
  name_template: '{{.Tag}}'

builds:
- id: event-reporter
  binary: event-reporter
  main: ./cmd/event-reporter
  goos:
    - linux
  goarch:
    - arm
  goarm:
    - "7"
  ldflags: -s -w -X main.version={{.Version}}

- id: service-watcher
  binary: service-watcher
  main: ./cmd/service-watcher
  goos:
    - linux
  goarch:
    - arm
  goarm:
    - "7"
  ldflags: -s -w -X main.version={{.Version}}

- id: version-reporter
  binary: version-reporter
  main: ./cmd/version-reporter
  goos:
    - linux
  goarch:
    - arm
  goarm:
    - "7"
  ldflags: -s -w -X main.version={{.Version}}

nfpms:
- vendor: The Cacophony Project
  homepage: http://cacophony.org.nz/
  maintainer: Cacophony Developers <coredev@cacophony.org.nz>
  description: Queue and report events to the Cacophony Project API
  license: GPL v3.0
  file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
  formats:
    - deb
  bindir: /usr/bin
  files:
    "_release/event-reporter.service": "/etc/systemd/system/event-reporter.service"
    "_release/service-watcher.service": "/etc/systemd/system/service-watcher.service"
    "_release/version-reporter.service": "/etc/systemd/system/version-reporter.service"
    "_release/org.cacophony.Events.conf": "/etc/dbus-1/system.d/org.cacophony.Events.conf"
  scripts:
    postinstall: "_release/postinstall.sh"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
